" general configs
set nocompatible " helpful default vim settings
set number " number lines
set ruler " show cursor position (row / col / %-of-file, in bottom right)
set incsearch " incremental search
set scrolloff=2 " minimum number of lines above/below cursor
set mouse=a " enable mouse
set winaltkeys=no	" allows mapping alt (meta) key shortcuts
" TODO: fix Alt+key also pressing key...

" set color scheme
try
  colorscheme desert256
catch
  colorscheme default
endtry

" space management
set expandtab " use spaces instead of tabs
set tabstop=2 " tabs are 2 spaces
set breakindent " indented line wrapping
" TODO: fix column numbers with indented text

" syntax highlighting
syntax on
filetype plugin on
filetype indent on

" searching
set smartcase " automagically figure out whether casing is important
set hlsearch " highlight search matches

" allow moving the cursor beyond the last character
set virtualedit=onemore

set timeoutlen=1000 " delay for key mapping (interpreted by vim)
set ttimeoutlen=5 " delay for keycodes (interpreted by terminal)

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" functions

" make <Home> clever about going to beginning of line vs. first nonblank character
function! SmartHome()
  let first_nonblank = match(getline('.'), '\S') + 1
  if first_nonblank == 0 " there are no whitespace characters
    " toggle between beginning and end of line
    return col('.') + 1 >= col('$') ? '0' : '^'
  endif
  if col('.') == first_nonblank " if currently at first nonblank
    return '0' " go to start of line
  endif
  " if word wrapping, go to beginning of 'displayed' line, else go to beginning of line
  return &wrap ? 'g^' : '^'
endfunction

" make <End> go to the end of the 'displayed' line, if word wrapping
function SmartEnd()
  return &wrap ? 'g$' : '$'
endfunction

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" key bindings
" see :help map-modes

" remove undesired mappings
map j <nop>
map K <nop>
map p <nop>
map P <nop>
map w <nop>
map W <nop>
map b <nop>
map B <nop>
map x <nop>
map d <nop>
map D <nop>
map V <nop>

" mode management
noremap t i| " insert
noremap T a| " append
noremap s v| " visual mode
noremap d V| " visual mode

vnoremap t I|
vnoremap T A|

" backspace key behavior
vnoremap <BS> "_d|
nnoremap <BS> "_x|

" cursor navigation
noremap u g<Up>|
noremap e g<Down>|
noremap n <Left>|
noremap i <Right>|
noremap <silent> <expr> l SmartHome()|
noremap <silent> <expr> y SmartEnd()|
noremap <silent> <expr> ; (winheight(0)/2) . "\<C-u>"| " half page up
noremap <silent> <expr> o (winheight(0)/2) . "\<C-d>"| " half page down
noremap <C-u> {|
noremap <C-e> }|
noremap <C-n> b|
noremap <C-i> w|

inoremap <C-u> <C-o>g<Up>|
inoremap <C-e> <C-o>g<Down>|
inoremap <C-n> <Left>|
inoremap <C-i> <Right>|
inoremap <silent> <expr> <C-l> "\<C-o>" . SmartHome()|
inoremap <silent> <expr> <C-y> "\<C-o>" . SmartEnd()|

" open new lines
noremap p O|
noremap P o|

" repeat search forward/backward
noremap f n|
noremap w N|

" copy/paste/undo
set clipboard=unnamed,unnamedplus
noremap c "+y| " copy selection to clipboard
noremap x "+d| " cut selection to clipboard
noremap v "+P| " paste
noremap V "+p| " paste
noremap z :undo<CR>| " undo
noremap Z :redo<CR>| " redo

" miscellaneous
noremap k zz| " center line
nnoremap Q @q| " replay the macro recorded by qq

nnoremap <Tab> :bnext<CR>
nnoremap <S-Tab> :bprevious<CR>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" key modifiers

" make up/down keys move one 'displayed' line up/down
noremap <Up> g<Up>|
noremap <Down> g<Down>|
noremap <Home> SmartHome()|
noremap <end> SmartEnd()|
