#!/usr/bin/python3
import sys

colors = {
  'fblack' : '000000',
  'fwhite' : 'ffffff',
  'black' : '111111',
  'white' : 'dddddd',
  'gray' : '777777',
  'red' : 'c11b17',
  'green' : '347c17',
  'blue' : '00688b',
  'yellow' : 'ffbb00'
}

try:
  print('#'+colors[sys.argv[1]])
except:
  exit(0)
