#!/usr/bin/env zsh

if [ $DESKTOP_SESSION == xmonad ]; then

  # start keyring daemon
  eval $(/usr/bin/gnome-keyring-daemon --start)
  export SSH_AUTH_SOCK

  # panel and power management
  xfce4-panel &
  xfce4-power-manager &

  # window compositing
  xcompmgr &

  # mouse and keyboard
  xsetroot -cursor_name left_ptr
  xmodmap ~/.Xmodmap
  numlockx off &

  # start some services
  #wicd-client --tray &
  #volnoti -t 1 &
  nm-applet &
  /usr/lib/xfce4/notifyd/xfce4-notifyd &
  emacs --daemon &
  fluxgui &

  # background
  feh --bg-fill /usr/share/backgrounds/background.jpg

fi

# start keyring daemon
if [[ -n "$DESKTOP_SESSION" ]]; then
  eval $(gnome-keyring-daemon --start)
  export SSH_AUTH_SOCK
fi
xset r 66
xset r rate 200 60
