#!/usr/bin/zsh

if ! [ $1 ]; then
  charge=`acpi | awk '{print $4}' | sed 's/[^0-9]//g'`
  echo $charge/100 | bc -l
elif [ $1 = state ]; then
  acpi | awk '{print $3}' | sed 's/[^a-Z]//g'
elif [ $1 = time ]; then
  time=`acpi | awk '{print $5}'`
  if [ ${#time} -le 8 ]; then
    echo ${time:0:5}
  else
    echo "?????"
  fi
fi
