#!/usr/bin/python3
import sys

# import arguments
try:
  height_total = int(sys.argv[1])
  width_total = int(sys.argv[2])
  portion_filled = float(sys.argv[3])
except:
  exit(0)

# compute filled rectangle width
width_filled = int(round(portion_filled*width_total))

# construct rectangles
output = '^r({1}x{0})^ro({2}x{0})'.format(
  height_total,width_filled,width_total-width_filled)

# return output rectangles
print(output)
