#!/usr/bin/python3
import sys

# import arguments
try:
  color = sys.argv[1]
  in_text = sys.argv[2]
except:
  exit(0)

# set text color
out_text = '^fg(%s)'%color + in_text + '^fg()'

# return formatted text
print(out_text)
