#!/usr/bin/sh

if ! [ $1 ]; then
  vol=`amixer get Master | tail -n 1 | awk '{print $5}' | sed 's/[^0-9]//g'`
  echo $vol/100 | bc -l
elif [ $1 = state ]; then
  amixer -c 0 get Master | grep dB | awk '{print $6}' | sed 's/[^a-z]//g'
fi
