#!/bin/sh

if [ $1 = dec ]; then
  xbacklight -dec 20
elif [ $1 = inc ]; then
  xbacklight -inc 20
elif [ $1 = dim ]; then
  xbacklight -set 20
elif [ $1 = max ]; then
  xbacklight -set 100
elif [ $1 = set ]; then
  xbacklight -set $2
elif [ $1 = med ]; then
  xbacklight -set 60
fi
