#!/bin/zsh

if ! [ $1 ]; then
  exit 0
fi

if [ $1 = term ]; then
  cmd= 
elif [ $1 = calc ]; then
  cmd="sage -q"
elif [ $1 = mixer ]; then
  cmd="alsamixer --view all"
else
  cmd=$1
fi

if [ $cmd ]; then
  xfce4-terminal --title="pad-$1" --command="$cmd"
else
  xfce4-terminal --title="pad-$1"
fi
