#!/bin/sh

if [ $1 = inc ]; then
	amixer -q set Master 5dB+
elif [ $1 = dec ]; then
  amixer -q set Master 5dB-
elif [ $1 = max ]; then
  amixer -q set Master 100%
elif [ $1 = min ]; then
  amixer -q set Master 0%
elif [ $1 = med ]; then
  amixer -q set Master 80%
elif [ $1 = set ]; then
  amixer set Master $3%
elif [ $1 = on ]; then
  amixer -q set Master on
elif [ $1 = off ]; then
  amixer -q set Master off
elif [ $1 = toggle ]; then
  if [ $state = on ]; then
    amixer -q set Master off
  elif [ $state = off ]; then
    amixer -q set Master on
  fi
fi
