#!/usr/bin/env sh

if [ "$#" -lt 1 ]; then
  exit 1
fi

delta=5
medium=50

device=sink
device_tag=@DEFAULT_SINK@
cmd=$1

if [ $1 = mic ]; then
  device=source
  device_tag=@DEFAULT_SOURCE@
  cmd=$2
fi

if [ $cmd = inc ]; then
  pactl set-$device-volume $device_tag +$delta%
elif [ $cmd = dec ]; then
  pactl set-$device-volume $device_tag -$delta%
elif [ $cmd = max ]; then
  pactl set-$device-volume $device_tag 100%
elif [ $cmd = min ]; then
  pactl set-$device-volume $device_tag 0
elif [ $cmd = med ]; then
  pactl set-$device-volume $device_tag $medium%
elif [ $cmd = toggle ]; then
  pactl set-$device-mute $device_tag toggle
elif [ $cmd = on ]; then
  pactl set-$device-mute $device_tag 0
elif [ $cmd = off ]; then
  pactl set-$device-mute $device_tag 1
fi
