#!/usr/bin/env sh

if [ "$#" -ne 1 ]; then
  exit 1
fi

if [ $1 = inc ]; then
  xbacklight -inc 10
elif [ $1 = dec ]; then
  xbacklight -dec 10
elif [ $1 = max ]; then
  xbacklight -set 100
elif [ $1 = min ]; then
  xbacklight -set 10
elif [ $1 = mid ]; then
  xbacklight -set 50
fi
